### ISSUE TITLE
Implement log rotation 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#381]
### Current Situation 

The `ct-app` fills up storage space continously. Therefore, the `ct-app` will hit the storage limit at some point and the app might crash due to that.  

### Task 

Implement a log rotation strategy that continously removes logs that are too old. Therefore, preventing the `app` from crashing due to potential storage problems.

**Comment by jeandemeusy** [comment]
Closing as not necessary.
