### ISSUE TITLE
Fix message statistics by peerId table in grafana 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#397]
For some peers in the `message statistics by peerId`  table the value for "relayed messages" is higher than the value for "expected messages". This should not happen as `expected messages` >= `relayed messages`. In other words, a peer cannot relay more messages than it is expected to relay.

**Comment by jeandemeusy** [comment]
Actually this *can* be the case. If a message come back when the `Postman` already moved to the next community node, then this new community node will see his `received_message` count increase by one, in addition to the ones he already relayed and received.

Fixing this should be done by tackling a refactoring of the app. (WIP)
