### ISSUE TITLE
Expose ct capacity as a metric on Grafana 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#400]
### Current Situation 

When we evaluated whether the ct-app can handle a 10x decrease in the ticket price we calculated how this would affect the capacity of the ct-app. For example, we calulated how long a given distribution would last with a 10x decrease in the ticket price.  We came to the conclusion that the ct-app can handle the increased amount of traffic. 

### Task 

Create a measure and visualize it through grafana that gives information about the current capacity of the ct-app.

**Comment by jeandemeusy** [comment]
This have been done by getting the average rabbitmq load over time. It is shown here https://grafana.ctdapp.net/d/ee699bf5-5d04-460b-9803-55e61b282162/ct-core?orgId=1 under "Capacity"
