### ISSUE TITLE
Node states are out of sync 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#403]
### Current Situation 
There is an issue related to possibly incorrect handling of on-chain events. The issue is documented here https://github.com/hoprnet/hoprnet/issues/5654 

The issue is not something that can be solved from the `ct-app` side. Therefore, `core` must solve the bug. However, the `core-team` will not implement a proper fix for the bug until hoprd version 2.1. The estimate from `core`  for version 2.1 is end of the year. 

The `ct-app` is not able to perform its job of distributing rewards in the network reliably due to this issue.

### Possible hack solutions until the problem gets solved

1. Cancel the distribution mechanism of the `ct-app` and airdrop rewards until the problem gets solved by core. 
2. Each ct-app instance closes all channels and re-opens them. This seems to solve the issue temporarly. However, the process of closing all channels and re-opening them given that each ct-app instance manages `300+` channels at this point will take approximately a day. Furthermore, closing all channels and re-opening them leads to a potential loss of tickets on the user side that is not observable for us. 
3. Same as `2`, but add code to the app that allows to identify nodes where we experience the problem and only close and re-open channels to these nodes. Same considerations as in `2` with the benefit of less downtime of the ct-app but the drawback that addtional code must be written that impements the feature.

**Comment by jeandemeusy** [comment]
Closing and reopening all channels has been done. Closing the issue
