### ISSUE TITLE
Adjust channel opening strategy 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/ct-research#406]
### Current Situation 

The `ct-app` checks whether nodes are available in the network using the `gather-peers` api call. If a node is part of the list the `ct-app` attempts to open a channel to this node we a default funding value of `60 wxHOPR`.   

###  ToDo 

To complement the planned fix of the core team for the following issue https://github.com/hoprnet/hoprnet/issues/5654 the `ct-app` must adjust its funding strategy. 

- The `ct-app` should still open a channel to a node seen in the network with a small default funding value. The amount must be decided.
- The `ct-app` should fund its channels at each distribution with the exact amount that should be distributed to nodes.

**Comment by MartinBenediktBusch** [comment]
@Teebor-Choka please link the relevant core issue describing the fix that the core team is going to implement for a better understanding of the issue.

**Comment by jeandemeusy** [comment]
This issue not has been tackled as it seams too costly to do. If at every distribution, to every single peer we fund (on-chain operation) all the channels, this would mean 400 peers * 4 nodes * 4 distribution = 6'400 on-chain operation/day. Realistically, it's way cheaper to have channels opened with a higher balance, and to top up when needed. However, the threshold value that triggers funding of a channel needs to be higher than the maximum value someone is expecting to receive for a given distribution, which is the case (funding triggers when balance goes bellow 15HOPR, no one is eligible for this much at a single distribution). This ensures that every peer will be able to redeem ticket from, at least, the last distribution.
