### ISSUE TITLE
Nodes is not getting relayed by the CT nodes

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/ct-research#473]
## Expected Behavior

If a node meets this criterion, it should receive relayed messages:

- The node is reachable by CT nodes
- It has opened at least one outgoing channel

## Current Behavior

Even if a node meets all the criteria, the last time it received relayed messages was on `2024-01-31 14:29:06 UTC`.

You will find details about the node and safe here: https://docs.google.com/document/d/1AAxXs_BRyM74K81DVNftBcYHJpu1Be_lS1KveAqiaPk/edit?usp=sharing

**Comment by jeandemeusy** [comment]
Issues were found with node-runners not having properly opened ports. They have been informed, and should help on this issue. Closing until next community request.
